### ISSUE TITLE
課題コピー用Actionsが動作しない

### ISSUE THREAD

**Issue by mickie895** [yumemi-inc/android-engineer-codecheck#21]
# 症状

ReadMe中の「課題取組方法」の中に記載されていたIssueのコピー用アクションが動作しませんでした。
動作時のログは下記に残っています。
https://github.com/mickie895/yumemi_codecheck/actions/runs/4826667679

## 再現方法

課題取組方法の手順で操作すれば発生すると思います。

## 確認済の情報

- リポジトリの公開状況に関わらずcreate-issue-labelsが失敗する
- リポジトリが非公開だとget-myrepo-issuesが追加で失敗する

## 現時点での推測

[ラベル作成用APIのサンプル](https://docs.github.com/ja/rest/issues/labels?apiVersion=2022-11-28#about-labels)の認証の部分と、
エラーコードが403であることから、認証方法が変更になっているのだと思われます。

※原因の確認後、動作確認を取っていたら引用部分がActionsを止めている可能性が高いことも発覚したので編集しました。

これで問題が無ければプルリクエストを提出いたします。

**Comment by mickie895** [comment]
@ykws
気になってしまっておおよそ調べたので共有しておきます。

## 検証の必要が少なそうな部分

### octokitのバージョンアップ

Workflow内で使われているoctokit/request-actionのバージョンが古かったために認証エラーを吐いていたようです。
octokit/request-actionの利用バージョンを「v2.1.7」にしてみたところ、エラーは止まりました。
また、create-issuesのジョブ内の認証の部分も修正しておけば問題なさそうです。
こちらは検証の必要が少なそうなので後で私がプルリクエストを出しておきます。

## 貴社内にて確認が必要そうな部分

### コピーする課題の絞り込み

このIssueの投稿時は本文に認証部分のサンプルの引用を行っていましたが、
その時にWorkflowを実行したら```Skip output 'issues' since it may contain secret.```といった警告が出て
Issueのコピーが行えませんでした。
今後同様の事例が発生したときのことを考えると、課題のみをコピーするようにフィルタリングしたほうが安全そうに見えました。

### Workflow permissionsの対応

詳しくは調べきれていませんが、おそらくWorkflowの実行権限も影響しています。
Workflowに必要な権限を追記するか、プロジェクト自体の権限を変更する旨を課題取り組み方法に追加するかの対応が必要そうです。

私は最初に動作しなかった時点で、Settings>Actions>General>Workflow permissionsと進み、
Read and write permissionsを選択しているので、これが原因でエラーが出たかどうかはチェックできていません。

### 値の受け渡し方法の廃止予定

5月末で現状の値の受け渡し方法が使えなくなるようです。
単純な置換で対応できるはずなので、余裕があれば私の方でも動作検証を行ってプルリクエストを出しておきます。

下記はWorkflow実行時に表示されたリンクです。

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by mickie895** [comment]
@ykws 

課題の絞り込みと値の受け渡し方法についても修正したので、#22のプルリクエストに追加しておきました。
ついでに課題間のリンクを貼る処理が、リンク番号を一桁しか見ないようになっていたのでそこも修正しています。

なお、自分の課題の方からAndroid Studioでコピペしたらフォーマッタが走って全体的に書き換えが発生したので、
変更点は少し見づらくなっていますがご了承下さい。

**Comment by blendthink** [comment]
↓ の対応で動作することを確認できました
https://github.com/yumemi-inc/android-engineer-codecheck/pull/24

残りは、set-output などの警告対応となります。

**Comment by mickie895** [comment]
「ついでに課題間のリンクを貼る処理が、リンク番号を一桁しか見ないようになっていたのでそこも修正しています。」
でエラーを仕込んでいたことを確認したので対応しました。プルリクエストの方のご確認をお願いします。

**Comment by blendthink** [comment]
@mickie895 @ykws 
#22 #23 のプルリクエストによって、こちらで記載してくださった懸念点などは、すべて対応済みの認識ですのでクローズさせていただきます！
もし、何か漏れている場合は再度オープンしていただければと思います。

お二人ともご対応ありがとうございました 🙇 😍
